import type { Metadata } from "next";
import { PublicEnvScript } from "next-runtime-env";
import { Roboto, Roboto_Mono } from "next/font/google";
import { cookies } from "next/headers";
import PopupProvider from "./components/Popup/PopupProvider";
import "./globals.css";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"], // regular, medium, bold
  variable: "--font-roboto", // optional for Tailwind
});

const robotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = cookies();
  const theme = (await (await cookieStore).get("theme")?.value) || "light";

  return (
    <html lang="en" data-theme={theme}>
      <head>
        <PublicEnvScript />
      </head>
      <body className={`${roboto.variable} ${robotoMono.variable} antialiased`}>
        <PopupProvider>{children}</PopupProvider>
      </body>
    </html>
  );
}
